# ShaderViewer lighting settings
lightIntensity=2.4
lightColorR=1
lightColorG=1
lightColorB=1
lightDirectionX=0.341882
lightDirectionY=-0.911685
lightDirectionZ=0.227921
cameraRelativeLight=0
lightPitchOffset=1
lightSideOffset=-1
ambientIntensity=0.1
lightWrap=0.285
scatterStrength=0.213
exposure=0.574
